name: CLUE Curriculum CI
on: push
jobs:
  s3-deploy:
      name: S3 Deploy
      needs:
      runs-on: ubuntu-latest
      steps:
        - name: Checkut Repository
        - uses: actions/checkout@v2
        - name: Use Node.js
        - uses: actions/setup-node@v2
          with:
            node-version: '18.x'
        - name: Deploy
        - uses: concord-consortium/s3-deploy-action@v1
          with:
            bucket: models-resources
            prefix: clue-curriculum
            awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
            awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            # Parameters to GHActions have to be strings, so a regular yaml array cannot
            # be used. Instead the `|` turns the following lines into a string
            topBranches: |
              ["main"]
